#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Olajide Badejo <olajideayomidebadejo@gmail.com>
#
# SPDX-License-Identifier: MIT
#
# The ISA staleness gate of Section 9.4.
#
# It regenerates the committed artifacts from include/NPU/Encoding/
# NPUISADescription.td and fails when they differ from what is in the tree.
# That is what makes drift a build failure rather than a thing somebody
# notices months later, and it is deliberately the same shape as the
# DIALECT_REFERENCE.md gate that has run since P1, so that this project has one
# staleness mechanism rather than two.
#
# Two files are covered:
#
#   docs/ISA_MANUAL.md    the opcode table and the validation check table,
#                         spliced between markers into hand written prose
#   docs/ISA_OPCODES.json the machine readable opcode list that
#                         scripts/check-reachability.py reads
#
# Usage:
#
#     bash scripts/check-isa-staleness.sh [BUILD_DIR]
#
# BUILD_DIR defaults to `build`, or to $NPU_BUILD_DIR when that is set.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

build_dir="${1:-${NPU_BUILD_DIR:-build}}"

artifacts=(docs/ISA_MANUAL.md docs/ISA_OPCODES.json)

if [ ! -d "${build_dir}" ]; then
  echo "check-isa-staleness: no build directory at ${build_dir}." >&2
  echo "check-isa-staleness: this gate regenerates the committed artifacts, so" >&2
  echo "check-isa-staleness: it needs a configured build. Configure one with" >&2
  echo "check-isa-staleness:" >&2
  echo "check-isa-staleness:     cmake -G Ninja -S . -B ${build_dir}" >&2
  exit 1
fi

for artifact in "${artifacts[@]}"; do
  if [ ! -f "${artifact}" ]; then
    echo "check-isa-staleness: ${artifact} is missing." >&2
    echo "check-isa-staleness: it is generated by" >&2
    echo "check-isa-staleness:" >&2
    echo "check-isa-staleness:     ninja -C ${build_dir} npu-isa-doc" >&2
    echo "check-isa-staleness:" >&2
    echo "check-isa-staleness: and committed." >&2
    exit 1
  fi
  # The comparison below is `git diff`, which says nothing at all about a file
  # git is not tracking. An untracked artifact would therefore pass this gate
  # forever while being regenerated on every run, which is the exact shape of a
  # check that reports success without checking anything.
  if ! git ls-files --error-unmatch "${artifact}" > /dev/null 2>&1; then
    echo "check-isa-staleness: ${artifact} is not tracked by git." >&2
    echo "check-isa-staleness: this gate compares the regenerated file against" >&2
    echo "check-isa-staleness: the committed one, and an untracked file has no" >&2
    echo "check-isa-staleness: committed version to compare against. Commit it." >&2
    exit 1
  fi
done

ninja -C "${build_dir}" npu-isa-doc

stale=0
for artifact in "${artifacts[@]}"; do
  if ! git diff --quiet -- "${artifact}"; then
    stale=1
  fi
done

if [ "${stale}" -ne 0 ]; then
  echo "::error::the committed ISA artifacts are stale."
  echo ""
  echo "include/NPU/Encoding/NPUISADescription.td changed and the generated"
  echo "files committed beside it did not. What moved:"
  echo ""
  git --no-pager diff -- "${artifacts[@]}"
  echo ""
  echo "Fix it with:"
  echo ""
  echo "    ninja -C ${build_dir} npu-isa-doc"
  echo ""
  echo "and commit the result in the same commit as the description change."
  exit 1
fi

echo "check-isa-staleness: docs/ISA_MANUAL.md and docs/ISA_OPCODES.json are up"
echo "check-isa-staleness: to date with include/NPU/Encoding/NPUISADescription.td."
